### SQL 2 : Find Items Bought

### Task

**Given** table with 2 columns: `buyer` and `item`.
- Buyer contains the name of buyer
- Item contains the name of item bought

**Return the name of items that is neither bought the most, nor bought the least.**

### Example

For example:

#### Example 1:

| buyer | item |
| --- | --- |
| Abdul | iPhone |
| Budi| Samsung |
| Charlie | Realme |
| Dimas | Realme |
| Erik | Samsung |
| Fikri | Realme |

Explanation:
- iPhone is bought 1 times.
- Samsung is bought 2 times.
- Realme is bought 3 times.

What is the item that is bought the most? Realme

What is the item that is bought the least? iPhone

So, what is the item that is NOT bought the most, and NOT bought the last? Samsung.

Your answer will be:

| item |
| --- |
| Samsung |

.

Jadi, carilah nama item yang **TIDAK DIBELI PALING BANYAK / PALING LAKU, dan juga TIDAK DIBELI PALING SEDIKIT / PALING GA LAKU**.

- iPhone PALING GA LAKU, cuma 1 kebeli
- Realme PALING LAKU, ada 3 kebeli

yang tengah-tengah siapa? Samsung. Berarti jawabannya:


| item |
| --- |
| Samsung |

##### Cukup 1x tulis `Samsung`, jangan ada duplikat dan kolom lain.
.

#### Example 2:

| buyer | item |
| --- | --- |
| Abdul | iPhone |
| Budi| Samsung |
| Charlie | Realme |
| Dimas | Realme |
| Erik | Samsung |
| Fikri | Realme |
| Gerry | Huawei |
| Hans | Huawei |
| Ihsan | Huawei |
| Jerome | Realme |

Explanation:
- iPhone is bought 1 times.
- Samsung is bought 2 times.
- Realme is bought 4 times.
- Huawei is bought 3 times

What is the item that is bought the most? Realme
What is the item that is bought the least? iPhone

So, what is the item that is NOT bought the most, and NOT bought the last?
Samsung and Huawei

Your answer will be:

| item |
| --- |
| Samsung |
| Huawei |

Jadi, carilah nama item yang TIDAK DIBELI PALING BANYAK / PALING LAKU, dan juga TIDAK DIBELI PALING SEDIKIT / PALING GA LAKU.

- iPhone PALING GA LAKU, cuma 1 kebeli
- Realme PALING LAKU, ada 4 kebeli

yang tengah-tengah siapa? Samsung, sama Huawei. Berarti jawabannya:

| item |
| --- |
| Samsung |
| Huawei |

##### Setiap nama produk hanya perlu ditulis 1x. Jangan dobel ya.

#### Example 3:

| buyer | item |
| --- | --- |
| Abdul | iPhone |
| Budi| Samsung |
| Charlie | Realme |
| Dimas | Realme |
| Erik | Samsung |
| Fikri | Realme |
| Gerry | Huawei |
| Hans | Huawei |
| Ihsan | Huawei |
| Jerome | Realme |
| Kevin | Huawei |

Explanation:
- iPhone is bought 1 times.
- Samsung is bought 2 times.
- Realme is bought 4 times.
- Huawei is bought 4 times

What is the item that is bought the most? Realme AND Huawei
What is the item that is bought the least? iPhone

So, what is the item that is NOT bought the most, and NOT bought the last?
Samsung only

Your answer will be:

| item |
| --- |
| Samsung |

Jadi, carilah nama item yang TIDAK DIBELI PALING BANYAK / PALING LAKU, dan juga TIDAK DIBELI PALING SEDIKIT / PALING GA LAKU.

- iPhone PALING GA LAKU, cuma 1 kebeli
- Realme dan Huawei PALING LAKU, ada 4 kebeli

yang tengah-tengah siapa? Samsung aja. Berarti jawabannya:

| item |
| --- |
| Samsung |

##### Setiap nama produk hanya perlu ditulis 1x. Jangan dobel ya.

### Space for Work

In [ ]:
### Tulis query jawaban pada online editor yang telah disarankan atau sesuai dengan preferensi ###

### Notes: anda perlu membuat query table data terlebih dahulu dengan memasukkan query di bawah###
CREATE TABLE item_bought (
    buyer TEXT NOT NULL,
    item TEXT NOT NULL
);

INSERT INTO item_bought (buyer, item) VALUES
('A', 'Asus'),
('B', 'Lenovo'),
('C', 'Lenovo'),
('D', 'Acer'),
('E', 'Acer'),
('F', 'Acer');