### SQL 1 : Find the 3rd Highest Salary

### Task

You will be given a table.

The table has 2 columns: `employee`, and `salary`.

**Please output the 3rd Highest Salary!**

### Example

#### Example 1:
| employee | salary |
| --- | --- |
| Abdul | 100 |
| Budi| 200 |
| Charlie | 100 |
| Dimas | 500 |

#### Answer 1:
`100`

Yup. Just output the 3rd highest salary. Please, do NOT give any Employee Name, do NOT give duplicate values. We know that 100 is the 3rd Highest Salary, and there are 2 Employees whose salary is 100. But we just care about the VALUE of the 3rd highest salary. Once again, no need to write duplicate values, no need to write the employee name

### Space for Work

In [ ]:
### Tulis query jawaban pada online editor yang telah disarankan atau sesuai dengan preferensi ###

### Notes: anda perlu membuat query table data terlebih dahulu dengan memasukkan query di bawah###
CREATE TABLE employee_table (
    employee TEXT NOT NULL,
    salary INTEGER
);

INSERT INTO employee_table (employee, salary) VALUES
('Alice', 11),
('Benn', 43),
('Charles', 33),
('Dorothy', 55),
('Emma', 22),
('Franklin', 33);